export const SET_BUN = "SET_BUN";
export const SET_INGREDIENT = "SET_INGREDIENT";
export const SET_PRICE = "SET_PRICE";
export const SORT_INGREDIENT = "SORT_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const REMOVE_BUN = "REMOVE_BUN";
export const CLEAR_CONSTRUCTOR = "CLEAR_CONSTRUCTOR";
