export const INGREDIENTS_FETCH = "INGREDIENTS_FETCH";
export const INGREDIENTS_ERROR = "INGREDIENTS_ERROR";
export const INGREDIENTS_SELECTED = "INGREDIENTS_SELECTED";
export const CLEAR_INGREDIENTS_SELECTEDS = "CLEAR_INGREDIENTS_SELECTEDS";
